name: ✨ Request a new feature
description: Suggest a feature or a new hook.
labels: ['feature']
title: 'feat: '
body:
  - type: input
    id: hook
    attributes:
      label: What is the target hook?
      description: the name of the hook that you want to add or modify.
      placeholder: useSomthing
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: Describe the new feature
      description: summarizing what feature you want to add.
    validations:
      required: true
