name: CI

on:
  workflow_dispatch:
  push:
    branches: [master]
    paths: ['packages/**']
  pull_request:
    types: [opened, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - run: pnpm install

      - name: Linting
        run: pnpm typecheck && pnpm lint

      - name: Running Tests
        run: pnpm test

      - name: Building
        run: pnpm build
