name: CI

on:
  workflow_dispatch:
  push:
    paths: ['package/src/**', 'tests/**']
  pull_request:
    types: [opened, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17.x, 18.x, 20.x]

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - run: pnpm install

      - name: Running Tests
        run: pnpm lint && pnpm test

      - name: Building
        run: pnpm build
